version: '3.3'
services:
  web:
    image: monolith:latest
    container_name: monolith
    networks:
      mynetwork:
        ipv4_address: 172.21.0.2
    build:
      dockerfile: Dockerfile.php
    volumes:
      - ../travelution-monolith:/var/www/html
      - ../travelution-monolith/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 80:80
  database:
    image: mysql
    container_name: mysql
    networks:
      mynetwork:
        ipv4_address: 172.21.0.3
    volumes:
      - ../travelution-monolith/database:/var/lib/mysql
      - ../travelution-monolith/travelution.sql:/docker-entrypoint-initdb.d/travelution.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: travelution_database
    ports:
      - 3306:3306
  rest-app:
    image: rest-app:latest
    container_name: rest-app
    volumes:
      - ../travelution-rest/src:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: ..
      dockerfile: travelution-config/Dockerfile.rest
    ports:
      - 8000:3000
    networks:
      mynetwork:
        ipv4_address: 172.21.0.4
  spa-app:
    image: spa-app:latest
    container_name: spa-app
    volumes:
      - ../travelution-subscription-app/src/vite-project:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: ..
      dockerfile: travelution-config/Dockerfile.spa
    ports:
      - 5000:5001
    networks:
      mynetwork:
        ipv4_address: 172.21.0.5
  restdb:
    image: mysql:latest
    container_name: mysql-rest
    restart: always
    volumes:
      - ../travelution-rest/travelution-rest.sql:/docker-entrypoint-initdb.d/travelution-rest.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: travelution_rest
    ports:
      - 5432:3306
    networks:
      mynetwork:
        ipv4_address: 172.21.0.6
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
  demo:
    external: true